# -*- coding: utf-8 -*-
"""Data Preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F4NdElF9QIOMB-rLSkk1cawK-Ij11Mt4
"""

df['math_score'].fillna(df['math_score'].mean(), inplace=True)
df['science_score'].fillna(df['science_score'].mean(), inplace=True)
df['attendance'].fillna(df['attendance'].mean(), inplace=True)
df['gender'].fillna(df['gender'].mode()[0], inplace=True)
print("\nMissing Values After Handling:")
print(df.isnull().sum())
df['math_score'] = pd.to_numeric(df['math_score'], errors='coerce')
df['science_score'] = pd.to_numeric(df['science_score'], errors='coerce')
df['attendance'] = pd.to_numeric(df['attendance'], errors='coerce')
df['exam_date'] = pd.to_datetime(df['exam_date'], errors='coerce')
print("\nExam Date Converted:")
print(df['exam_date'].head())
def remove_outliers(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR
    return data[(data[column] >= lower_limit) &
                (data[column] <= upper_limit)]
df = remove_outliers(df, 'math_score')
df = remove_outliers(df, 'science_score')
print("\nDataset After Removing Outliers:")
print(df)
duplicates = df.duplicated().sum()
print("\nNumber of Duplicate Rows:", duplicates)
df = df.drop_duplicates()
print("Duplicates Removed Successfully")