# -*- coding: utf-8 -*-
"""Data Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LsZzpWTdu6Ly7zhNiZtrLsykmSPJbNQK
"""

df['average_score'] = (
    df['math_score'] + df['science_score']
) / 2
print("\nDataset with Average Score:")
print(df.head())
top_students = df.sort_values(
    by='average_score',
    ascending=False
).head(5)
print("\nTop 5 Students Based on Average Score:")
print(top_students)
correlation = df['attendance'].corr(df['average_score'])
print("\nCorrelation Between Attendance and Average Score:")
print(correlation)
gender_avg = df.groupby('gender')[
    ['math_score', 'science_score', 'average_score']
].mean()
print("\nAverage Marks Grouped by Gender:")
print(gender_avg)