# -*- coding: utf-8 -*-
"""NumPy Operations

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ygdcCGs4NJg-g5HHX07OcAutexGhXR53
"""

df = pd.read_csv("students_data.csv")
math_scores = np.array(df['math_score'])
print("Math Score Array:")
print(math_scores)
print("\nStatistics of Math Scores")
print("Mean:", np.mean(math_scores))
print("Median:", np.median(math_scores))
print("Maximum:", np.max(math_scores))
print("Minimum:", np.min(math_scores))
normalized_scores = (math_scores - np.min(math_scores)) / \
                    (np.max(math_scores) - np.min(math_scores))
print("\nNormalized Math Scores:")
print(normalized_scores)