# -*- coding: utf-8 -*-
"""Pandas Exploration

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17_57dHJn6Rp5GNqn4tj4KonMKjmzbKuk
"""

print("\nFirst 5 Rows:")
print(df.head())
print("\nData Types:")
print(df.dtypes)
print("\nMissing Values:")
print(df.isnull().sum())
print("\nStudents with Attendance Below 70%:")
low_attendance = df[df['attendance'] < 70]
print(low_attendance)